### PR TITLE
Reverted to use deck brew’s images since they are fixed and more reli…

### PR DESCRIPTION
**Pull request by njkremer**
…able.

### CODE REVIEW

**Comment by njkremer** [comment]
Hey Jared, would you be able to merge this pull request and push to your heroku pretty please :)

**Comment by njkremer** [comment]
Can you please merge this pull request and push to your heroku pretty please :)

**Comment by MrMint** [comment]
🎉

**Comment by MrMint** [comment]
Deployed, let me know if there are any issues.

**Comment by njkremer** [comment]
No issues, works like a charm (awwyiss)

**Comment by njkremer** [comment]
Thanks!

**Pull request merged**
